### ISSUE TITLE
Support Extension methods

### ISSUE THREAD

**Issue by mneumann** [savi-lang/savi#210]
Allow to add methods to existing classes within the local scope.

For example, some of my code expects a `Bytes#push_bytes` method which does not exist upstream. Or maybe some methods will not be accepted upstream very quickly. In my code I can still use the method as long as it is defined as an extension method:

```savi
:extend class Bytes
  :fun push_bytes(...)
    ...

// and within the same package:

Bytes
  .new_iso
  .push_bytes(b"...")
```

The extension methods are only available within the same package. 

Extension methods exist in C#. In Rust, you can use "extension" traits to achieve the same. Extension traits in Rust or Extension methods in C# can be imported into some scope, whereas the proposal above would only work locally.

**Comment by jemc** [comment]
I think this need would be taken care of by #160 - do you agree?

**Comment by jemc** [comment]
Note that #160 does not propose exactly the same feature you've proposed here (extension methods only visible in a local scope), because I have concerns about how that kind of feature would interact with structural typing - it's hard to cleanly delineate from a semantics perspective where exactly the type starts/stops being a subtype of an interface that it only aligns with in a particular local scope.

Instead #160 proposes global visibility of the extensions, and package/dependency-level auditability/accountability to discourage frivolous extensions. Generally, by convention, such extensions should only be in end-user application packages rather than in reusable library packages, because such a library package would easily run into conflicts with other library packages that attempt to extend in the same way, or with new versions of the base type that have the given method name.

So, by convention, extensions should only occur in a library package if:
- :a: that library is under alpha-level development and just wants to "move fast" and not be stable, or..
- :b: that library's main purpose is to extend types from another library, and it is widely recognized in the community as being the "rightful owner" of those extensions, such that other libraries don't clobber the extensions. Even then, this is kind of a cringeworthy case, in my opinion, but there may be specific use cases where this could be considered appropriate.

In an application package, one can be a bit more liberal with the use of extensions, since the application is the final end point that integrates all its library packages together, and thus should have the level of flexibility to extend as needed, taking on the responsibility of reworking those extensions if/when conflicts from changes to the base type arise.

**Comment by jemc** [comment]
If we wanted to support the kind of local-only feature you've proposed here, we'd need to carefully discuss how structural typing ties into the design.

I suspect that it will be hard to find a satisfactory answer to those questions in the design, but we're more than welcome to continue discussing those here.

But personally I think the core "move fast in a non-stable code base" use case you raised would still be served adequately by the design in #160, so if you agree, we can close this ticket.

**Comment by mneumann** [comment]
@jemc I think #160 makes perfect sense. I am closing in favor of #160
