### ISSUE TITLE
Compiler error on Fedora: "failed to find crtbegin.o"

### ISSUE THREAD

**Issue by FinnRG** [savi-lang/savi#249]
I installed the savi compiler through asdf, but I'm unable to run any savi code due to the following error:
`Savi compiler error occured with message "failed to find crtbegin.o". Consider submitting an issue ticket.`
I was able to locate `crtbegin.o` under `./usr/lib/gcc/x86_64-redhat-linux/11/crtbegin.o`.

savi version: 20220304b
llvm version: 13.0.0

**Comment by jemc** [comment]
@FinnRG - thanks for your interest in Savi!

This particular issue should be a quick fix for me (I just need to add a search path to the linker invocation to match the redhat convention). I can have a fix released later today.

However, since you're new to Savi I'll also mention that at this particular time I'm in the midst of significant changes related to adding a package management system and moving the standard libraries (see #156 and #44). So there may be some rough edges at the moment for setting up an example project to explore. I am working this week on adding some more convenience commands and some documentation that should help guide new users like yourself.

In the meantime, I invite you (and any others reading this) to stop by [our chat service](https://savi.zulipchat.com) if you have any questions about how to proceed or want live assistance with anything Savi-related. Or continue to file issue tickets as needed if that is more convenient for you.

As I mentioned above, I'll get a fix out for this later today and ping you back when it's ready.

**Comment by jemc** [comment]
I was able to [reproduce this bug using new CI automation on the `asdf-savi` repo](https://github.com/savi-lang/asdf-savi/runs/5470184425?check_suite_focus=true), so now I have a way to prove when it's working and to detect/prevent regressions.

I'll go ahead and add the search path changes now to fix the bug.

**Comment by FinnRG** [comment]
Thx, savi now works as expected

**Comment by jemc** [comment]
Thanks for testing locally!

I was also able to confirm success on the CI job I added in the `asdf-savi` repo: https://github.com/savi-lang/asdf-savi/pull/1
