### ISSUE TITLE
Add String interpolation

### ISSUE THREAD

**Issue by tonchis** [savi-lang/savi#84]
Similar to how Ruby provides String interpolation with the `#{}` syntax, it would be nice having something similar in Mare.

**Comment by jemc** [comment]
First thing to design is the syntax:

Options I have seen in other languages for String interpolation:
- `#{}` - Ruby, Elixir, Crystal
- `${}` - JavaScript, Dart, Kotlin, Scala
- `\()` - Swift

Honestly, I kind of like the Swift approach even though it seems to be the odd one out - I like the consistency of the `\` being the only thing that triggers something special to happen in a String. That is, all characters in a string are always literal unless they're part of a `\`-initiated special sequence. There's something satisfying about that.

That said, I'd be okay with either of the other ways as well. There's not really a clear single most common approach in the survey of languages. Although I suppose if you treat all the Ruby-likes as one language, then `${}` comes out the winner, but I'm not sure I care much about that distinction.

---

The other thing to design is what happens to the expression inside the interpolation if it is not already a String. String interpolation is not very useful if you require that everything in it must already be a string, so it seems clear that if we're going to do this we want to have some kind of coercion to a String that happens, that can at least convert some subset of types to a String for the purpose of interpolation.

So what is the mechanism by which those things get converted to a String for concatenating in the interpolation? Well, we already have the `Inspect` primitive for converting things to strings for debugging purposes, so on its face it seems like that would be a good approach to align with.

However, I think if we do that, then we run into the same problem that Ruby had that made them have a distinction between `to_s` and `inspect`. For many types these will output the same string, but for some it's different in an important way. In particular, `String` itself is an important case of difference.

In Ruby, `String#to_s` will just return the same string itself, but `String#inspect` returns a new string that looks like the source code that would produce the original string, with surrounding quotes and escape codes:
```ruby
puts "Hello,\tWorld".to_s
# => Hello,	World
```
```ruby
puts "Hello,\tWorld".inspect
# => "Hello,\tWorld"
```

Ideally we could avoid the conceptual duplication between `to_s` and `inspect` but in practice I'm not sure how to do that without having the problem of it either being unsuitable for debugging (i.e. only having the `to_s` behavior) or unsuitable for interpolation (i.e. only having the `inspect` behavior).

**Comment by mneumann** [comment]
FYI, Rust uses `{}` as interpolation "marker":

```rust
format!("{} {}", "hello", "world");
```

It supports different formatting modes, i.e. `{:?}` is using the `Debug` trait for formatting the argument (similar to `inspect` in Ruby), whereas `{}` uses the `Display` trait ("`to_s`"). You can also name arguments:

```rust
format!("{first:?} {second}", first="hello", second="world");
```

Or supply further format arguments:

```rust
println!("({:<7.2})", 42.0); // => "(42.00  )"
```

"<7" will left-align with width 7 and ".2" will use two trailing digits as precision.

And all this is not built into the language but implemented as a macro. 

The advantage of this vs. 
```ruby
"(#{42.0.to_s.ljust(7)})"
```

is that you do not have to allocate intermediate strings.

**Comment by jemc** [comment]
I tend to see number formatting as a mostly separate use case, which I wasn't necessarily planning to handle with the same mechanism as "normal" string interpolation.

---

I do think the Rust approach you have outlined is elegant, though not quite as concise for the case of "basic" string interpolation with no "extra" formatting options involved.

At this time, our macros system in Mare is not full-featured enough to pull it off in the same way that Rust does, though it's something to aspire to in the future. I think such a formatting system could potentially coexist with a simpler form of non-formatting string interpolation.

---

I agree that it's very important to avoid designing for a pattern that allocates intermediate strings and throws them away.

It's worth noting for those reading along that the intermediate allocation in the Ruby example above arises not really because of the string interpolation approach, but because of the number formatting approach - the fact that `ljust` in the example is being used as a separate operation from the first one that converts the number to a string.

That is, the intermediate allocation issue could be avoided in that example by having the justification and conversion happen at the same time, using something like this, just shown as a potential approach and not necessarily a full endorsement:

```ruby
"(#{42.0.format(precision: 2, ljust: 7)})"
```

**Comment by mneumann** [comment]
in the last example, you'd still allocate a string. think about directly writing to `IO` (in Rust `println!(...)` for instance). but lets concentrate on string interpolation...

as for string interpolation, I can see the consistency of `\( )` that you are describing appealing, though my eyes are probably more used to `${}` or `#{}`.  Sometimes when writing Rust code, typing in `"{:?}"` slows me down and keeps my finger(s) pretty busy (I type all 4 characters with the same little finger).

IMHO whatever you choose, most important is that it is quick and easy to type in as I expect String interpolation to be a very frequent pattern. I believe `\()` might be easier to type in with  less finger movements as it uses three distinct fingers... and overall you seem to prefer `(`s over `{` in Mare, so that would speak for `\()` as well.

**Comment by jemc** [comment]
@mneumann I'm glad you're pressing on this point about allocations, because there's actually a way to pull off the above example with no additional string allocations, including the formatted number being written directly into the final target string buffer.

---

Let's imagine that in addition to the `as_string` method (which I'll use in this comment to refer to the same idea referred to in Ruby by the `to_s` method), we have another method which types can also optionally implement:
```
:fun into_string(target String'iso) String'iso
```

This method, if it is present on the type, would be preferred by the generated code that writes into the interpolated string buffer, so that any type which implements this method can avoid creating an intermediate `String` object.

Composite types can delegate to the `into_string` of their elements, each in turn, interleaving whatver extra elements the composite type adds into the total string representation being used.

However, if `into_string` is not present, we will fall back to using `as_string`, which would return a `String` object that can be appended to the `String'iso` simply.

---

But we can go even further with preventing allocations.

Keen readers will note that if we do not know the final needed size of the buffer being built after everything is written into it, then we run the risk of allocating a starting buffer that is not an optimal size. If the starting buffer is much too large, we have wasted bytes right off the bat. If the starting buffer is too small, we will have to reallocate a larger buffer partway through the process, maybe even multiple times.

To prevent this, a type that implements `into_string` can also optionally implement `into_string_space`, which would serve as a hint for the expected byte size for the generated code to use when determining the right amount of space to allocate in the starting buffer.

```
:fun into_string_space USize
```

This will allow individual types to determine how best to optimize their string representation - they may know the exact size or they may have a decent probabilistic idea that will usually be large enough without being exceedingly large. It may be statically known (in which case the LLVM inlining and constant expression handling can probably benefit us to the same degree as the Rust compiler probably benefits for statically known sizes) or it may be dynamically calculated (in which case both us and Rust will need to be calculating the total space at runtime).

Composite types can delegate to the sum of the `into_string_space` of their elements, plus whatever "overhead" they add in the total string representation being used.

---

Now, the keen reader may be wondering how, in our earlier example, we can successfully leverage this approach to avoid the intermediate allocation - if there is no intermediate `String` object, then what is the value of the `42.0.format(precision: 2, ljust: 7)` expression?

The answer, if we want to take advantage of this optimization, is that it returns a stack-allocated struct that "knows how" to do `into_string` and `into_string_space` with the given precision and justification. Since we now have stack-allocated structs (which Pony doesn't yet), we can pull this off without making an allocation. And LLVM inlining and related optimizations can probably even eliminate the struct from the stack as well.

---

Put it all together, and I think we can get rather close (if not all the way) to the Rust level of optimization for these operations.

**Comment by jemc** [comment]
Keeping in the theme of optimizing performance while retaining convenience, I thought of an additional optimization special case handling to consider:

When a user is implementing `:fun into_string`, they're going to be sometimes tempted to do things like this, appending interpolated strings onto the target:
```mare
:fun into_string(target String'iso) String'iso
  target << "\(@foo) \(@bar) \(@baz)"
  --target
```

But this is not optimal the current plan because it results in an extra string allocation for the intermediate interpolated string, with the implicit generated code doing something like this:
```mare
:fun into_string(target String'iso) String'iso
  interpolated_string = String.new_iso
  interpolated_string.reserve(
    2 + @foo.into_string_space + @bar.into_string_space + @baz.into_string_space
  )
  interpolated_string = @foo.into_string(--interpolated_string)
  interpolated_string << " "
  interpolated_string = @bar.into_string(--interpolated_string)
  interpolated_string << " "
  interpolated_string = @baz.into_string(--interpolated_string)
  target << --interpolated_string
  --target
```

It would be far better if we could instead generate this, adding the interpolated pieces directly into the target:
```mare
:fun into_string(target String'iso) String'iso
  target.reserve(
    target.size + 2 + @foo.into_string_space + @bar.into_string_space + @baz.into_string_space
  )
  target = @foo.into_string(--interpolated_string)
  target << " "
  target = @bar.into_string(--interpolated_string)
  target << " "
  target = @baz.into_string(--interpolated_string)
  --target
```

Though I'm undecided as of yet on the best way to detect this special case to optimize both for ergonomics and not violating the principle of least surprise.

Some ideas I've thought about:
- detect the case of an interpolated string as the argument of `String.<<` and implicitly apply this optimization
- detect the case of an interpolated string where the first interpolated piece is a consumed string variable (e.g. `"\(--target)\(@foo) \(@bar) \(@baz)"), and implicitly apply this optimization
- introduce some new syntax for this optimization and encourage users to use that one instead of either of the above approaches (it would have to be more convenient/ergonomic than the above two options in order to make the user not be tempted to skip it and sacrifice perfformance.

**Comment by mneumann** [comment]
@jemc 

In Rust, the two cases you are describing are two different macros: 

`write!(io, formatString, *args) -> Ok(Usize) | Error` 

and

`format!(formatString, *args) -> String'iso`

So you can always add specialized macros to Mare that will be more optimal in certain cases.

One thing you could do is to make `<<` a macro invocation instead of a method call.

So,

```mare
target << "a: \(123), b: \(234)"
```
would be rewritten to

```
macro_<<(target, (("a: ", ", b: "), (123, 234)) )
```

and the macro will call the "<<" method (see the ".dot" notation below distinguishing the macro invocation from the method call):

(Note that the interpolated string is syntactic sugar for the nested tuple `(("a: ", ", b: "), (123, 234))`)

```mare
:let estimated_byte_size = target.byte_size("a: ") + target.byte_size("b: ") + target.byte_size(123) + target.byte_size(234)

target.items_hint(4) // we are going to write 4 items
target.bytes_hint(estimated_byte_size) // we are going to write that much bytes

// now on to writing each item to the `Writer`
target.<< "a: "
target.<< 123 // the << method would need to be overloaded not just for strings but other types...
target.<< "b: "
target.<< 234

target
```

Note that the "<<" method in this case would be something more general than just `into_string`, the receiver could be a String, IO or Array etc.

```mare
:trait Writer
  :: estimated number of items that will be written by following `<<` operations.
  :fun items_hint(estimated_items : USize)

  :: estimated total number of bytes that will be written by following `<<` operations.
  :fun bytes_hint(estimated_bytes : USize)

  :: calculates the required size in bytes to write `item` or `None` if unknown.
  :: 
  :fun byte_size(item : Stringable) : USize | None

  :fun "<<"(item : Stringable)
```

By having separate `items_hint` and `bytes_hint`, writing into a `Array(String)` could be optimized, too.


In the above example, the interpolated string is represented by a data structure. In Javascript, template literals like "`before ${123} after`" are roughly represented as `[["before ", " after"], [123]]`. That's probably the way you want to represent it in the compiler. Exposing this to the user is bad because it involves Array allocations and unless you have stack allocated arrays (which implies lifetimes) it will be too expensive.


Overall, it seems to be much simpler to separate the two use cases in the way Rust is doing it. The required macros can be initially hard-coded in the compiler. But, I would not like having interpolated strings plus these two macros (`format` and `write`).

**Comment by jemc** [comment]
I've been thinking a lot over the past 24 hours about how to better optimize the case I mentioned in https://github.com/savi-lang/savi/issues/84#issuecomment-872413861

I've thought of many language changes that could potentially help with that, but they're all rather unfortunate in various ways - often being overly complicated, overly magical, or breaking encapsulation too much.

I've come to the general decision that those optimizations would be better done by the compiler under the hood - likely at the LLVM level after inlining has occurred.

Basically, we want to track provenance of any `String'iso` that gets subsumed into another `String'iso`, and try if possible to merge them into the same underlying buffer allocation (that is, at different pointer offsets into the same allocation). Probably as a custom LLVM pass enriched by metadata attached by the Savi compiler, if necessary (or maybe LLVM is already smart enough to recognize the isolation and merge the pointers itself, after inlining is done).

Overall, I think I want to proceed with the plan I laid out in this comment: https://github.com/savi-lang/savi/issues/84#issuecomment-872413861 . It's not perfect but I've been unable to come up with anything better.

**Comment by jemc** [comment]
#282 implements this feature and will close this ticket.

I've opened #283 to track the idea about LLVM string provenance tracking to further optimize string allocations.
